### ISSUE TITLE
error installing rubyzip

### ISSUE THREAD

**Issue by sbagmeijer** [poise/poise-archive#4]
I try to use this cookbook with aws opsworks but it keeps failing with the following error:

```
[2016-10-24T13:30:51+00:00] INFO: Processing chef_gem[rubyzip] action install (/var/chef/runs/7f0df452-daea-4452-b5ee-53b77e4a8d11/local-mode-cache/cache/cookbooks/poise-archive/files/halite_gem/poise_archive/archive_providers/zip.rb line 47)
 
================================================================================
Error executing action `install` on resource 'chef_gem[rubyzip]'
================================================================================
 
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '127'
---- Begin output of /opt/chef/embedded/bin/gem install rubyzip -q --no-rdoc --no-ri -v "1.2.0" ----
STDOUT: 
STDERR: sh: /opt/chef/embedded/bin/gem: No such file or directory
---- End output of /opt/chef/embedded/bin/gem install rubyzip -q --no-rdoc --no-ri -v "1.2.0" ----
Ran /opt/chef/embedded/bin/gem install rubyzip -q --no-rdoc --no-ri -v "1.2.0" returned 127
 
Cookbook Trace:
---------------
/var/chef/runs/7f0df452-daea-4452-b5ee-53b77e4a8d11/local-mode-cache/cache/cookbooks/poise-archive/files/halite_gem/poise_archive/archive_providers/zip.rb:47:in `install_rubyzip'
/var/chef/runs/7f0df452-daea-4452-b5ee-53b77e4a8d11/local-mode-cache/cache/cookbooks/poise-archive/files/halite_gem/poise_archive/archive_providers/zip.rb:41:in `block in check_rubyzip'
/var/chef/runs/7f0df452-daea-4452-b5ee-53b77e4a8d11/local-mode-cache/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `instance_eval'
/var/chef/runs/7f0df452-daea-4452-b5ee-53b77e4a8d11/local-mode-cache/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `subcontext_block'
/var/chef/runs/7f0df452-daea-4452-b5ee-53b77e4a8d11/local-mode-cache/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:67:in `notifying_block'
/var/chef/runs/7f0df452-daea-4452-b5ee-53b77e4a8d11/local-mode-cache/cache/cookbooks/poise-archive/files/halite_gem/poise_archive/archive_providers/zip.rb:40:in `rescue in check_rubyzip'
/var/chef/runs/7f0df452-daea-4452-b5ee-53b77e4a8d11/local-mode-cache/cache/cookbooks/poise-archive/files/halite_gem/poise_archive/archive_providers/zip.rb:38:in `check_rubyzip'
/var/chef/runs/7f0df452-daea-4452-b5ee-53b77e4a8d11/local-mode-cache/cache/cookbooks/poise-archive/files/halite_gem/poise_archive/archive_providers/zip.rb:32:in `unpack_archive'
/var/chef/runs/7f0df452-daea-4452-b5ee-53b77e4a8d11/local-mode-cache/cache/cookbooks/poise-archive/files/halite_gem/poise_archive/archive_providers/base.rb:70:in `block in action_unpack'
/var/chef/runs/7f0df452-daea-4452-b5ee-53b77e4a8d11/local-mode-cache/cache/cookbooks/poise-archive/files/halite_gem/poise_archive/archive_providers/base.rb:65:in `action_unpack'
 
Resource Declaration:
---------------------
# In /var/chef/runs/7f0df452-daea-4452-b5ee-53b77e4a8d11/local-mode-cache/cache/cookbooks/poise-archive/files/halite_gem/poise_archive/archive_providers/zip.rb
 
47:         chef_gem 'rubyzip'
48:       end
 
Compiled Resource:
------------------
# Declared in /var/chef/runs/7f0df452-daea-4452-b5ee-53b77e4a8d11/local-mode-cache/cache/cookbooks/poise-archive/files/halite_gem/poise_archive/archive_providers/zip.rb:47:in `install_rubyzip'
 
chef_gem("rubyzip") do
package_name "rubyzip"
action [:install]
retries 0
retry_delay 2
default_guard_interpreter :default
declared_type :chef_gem
cookbook_name "bbr_bastion"
gem_binary "/opt/chef/embedded/bin/gem"
end
 
Platform:
---------
x86_64-linux
```

this is what I add to my book:

> poise_archive 'http://aws-cloudwatch.s3.amazonaws.com/downloads/CloudWatchMonitoringScripts-1.2.1.zip' do
>   destination '/opt'
> end

do you maybe know how I could fix this?

**Comment by coderanger** [comment]
Unfortunately `chef_gem` not working is unrelated to this cookbook, but it probably an issue with how OpsWorks installs Chef. You'll have to take it up with Amazon support or stop using OpsWorks.
